server:
       port: 8761
       
eureka:
   instance:
      hostname: localhost       
   client:
      registerWithEureka: false
      fetchRegistry: false
      service-url: 
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   
      
spring:
  bootadmin:
   context-path: http://localhost:8761/admin
eureka:
   instance:
        leaseRenewalIntervalInSeconds: 10
eureka:
   client:
     registerWithEureka: false
eureka:
  client:
    fetchRegistry: false
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka