server:
   port: 8081
   
#eureka:
# client:
#  serviceUrl:
#   defaultZone: http://localhost:8761/eureka/

eureka:
 client:
   register-with-eureka: true
   fetch-registry: true 
   serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 instance:
    hostname: localhost
  

logging:
  pattern: 
console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"   
   
   