server:
  port: 8080
  
eureka:
 client:
   register-with-eureka: true
   fetch-registry: true 
   serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 instance:
    hostname: localhost  
      
     
logging:
  pattern: 
   console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
   
#spring:
#     boot: 
#       admin:
#         url: http://localhost:8761/admin
         
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employee/**
        filters:
        - RewritePath=/employee/(?<path>.*), /$\{path}          